sonar.projectKey=react-frontend
sonar.projectName=react-frontend

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/*.{test,spec}.{ts,tsx}

sonar.exclusions=\
dist/**,\
coverage/**,\
node_modules/**,\
src/main.tsx,\
src/**/*.css,\
src/tests/**/services/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8