sonar.projectKey=react-frontend
sonar.projectName=react-frontend

sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.tests=src

sonar.test.inclusions=src/**/*.{test,spec}.{ts,tsx}

sonar.exclusions=\
dist/**,\
coverage/**,\
node_modules/**,\
src/main.tsx,\
src/**/*.css,\
src/tests/**,\
src/types/**,\
src/assets/**,\
src/components/layout/**,\
src/components/Labels/**,\
src/redux/store.ts,\
src/utils/toast.ts,\
src/routes/**,\
src/pages/PageNotFound.tsx,\
src/pages/Home.tsx,\
src/pages/AboutPage.tsx,\
src/components/home/NavBar.tsx,\
src/components/DeleteModal.tsx,\
src/services/HandleBookAppointments.ts,\
src/hoc/withUsersMap.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
