export const labels: Record<string, string> = {
  "admin-dashboard": "Admin Dashboard",
  "doctor-dashboard": "Doctor Dashboard",
  "patient-dashboard": "Patient Dashboard",
  "nurse-dashboard": "Nurse Dashboard",
  "admin-users": "Users",
  "admin-bills": "Bills",
  "admin-medicines": "Medicines",
  "admin-doctors": "Doctors",
  "admin-patients": "Patients",
  "admin-nurses": "Nurses",
  "admin-departments": "Departments",
  "admin-appointments": "Appointments",
  "doctor-appointments": "Appointments",
  "patient-appointments": "My Appointments",
  "book-appointment": "Book Appointment",
  "nurse-appointments": "Appointments",
  "patient-book-appointment": "Book appointment",
  "patient-bills": "My bills",
  "patient-medical-records": "My medical records",
  "medical-records": "Medical Records",
  "admin-profile": "Profile",
  "doctor-profile": "Profile",
  "patient-profile": "Profile",
  "nurse-profile": "Profile",

  add: "Add",
  edit: "Edit",
  login: "Login",
};
